name: Python and R Formatting

on: [push]

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    # Setup Python and format Python code
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install black and isort
      run: |
        python -m pip install black isort
    - name: Format code with black
      run: black .
    - name: Sort imports with isort
      run: isort .
    
    # Setup R and format R code
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'
    - name: Install styler
      run: |
        R -e 'install.packages("styler", repos="http://cran.rstudio.com/")'
    - name: Format R code with styler
      run: |
        R -e 'styler::style_dir()'
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply auto-formatting
        branch: ${{ github.head_ref }}
